---
- hosts: webservers 
  become: True
  tasks:
    
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
    - name: Start Apache server
      service:
        name: httpd
        state: restarted
        enabled: True
...
