--- 
- 
  hosts: webservers
  service: 
    - 
      enabled: true
      name: httpd
      state: started
  tasks: 
    - 
      copy: 
        dest: /var/www/html/
        src: index.html
      name: "Deploy static website"
    - 
      name: "restart service"
