---
- hosts: webservers 
  become: True
  tasks:
    - name: Deploy static website
      copy:
        src: index.html
        dest: /var/www/html/
    - name: restart service
  service:
    - name: "httpd"
      state: started
      enabled: yes
    register: restart
   - debug:
      var: restart.stdout
